# STAT40800 Data Programming with Python
## Dr. Áine Byrne


# Week 3
Last week we introduced modules and packages and began to look at the Numpy package. Numpy is particularly good for linear alegbra and manipulating array. This week we will delve a little deeper into Numpy and also introduce the pandas package.

In [1]:
import numpy as np

## Linear algebra in Python
We will predominantly be using Numpy for linear algebra, but you should be aware of Scipy which shares a lot of Numpy's functionalities.

* The main goal of NumPy is to enable computation with arrays, such as creating, editing, sorting, etc
* The main goal of SciPy is to enable scientific computation with data
* They both contain functions for linear algebra, almost always with the same name and functionality
* We're going to continue using the NumPy linear algebra functions, but be aware that most commands could be re-run with the SciPy package instead

Last week we encountered some of the Numpy functions for creating matrices:

In [6]:
A = np.array((range(5),[10]*5))
B = np.random.rand(5,5)#5*5 matrix
C = np.ones((5,2))# first argument defines rows another argument defines the rowscreate  matrix with one values at defined dimensions
D = np.eye(5)#to create identity matrix

In [10]:
print(A)

[[ 0  1  2  3  4]
 [10 10 10 10 10]]


In [19]:
#non accesed exercise 
import numpy as np
X = np.array((range(1,5),[2,4,6,8],[3,6,9,12]))
Y =np.array(([2,2,2],[2,2,2],[2,2,2],[2,2,2]))
# print(X)
# print(Y)
print(X.dot(Y))

[[20 20 20]
 [40 40 40]
 [60 60 60]]


In [8]:
print(C)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
print(D)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
print(A)

[range(0, 5) 50]


In [7]:
print(B)

[[4.13091001e-03 8.47567321e-01 9.22262013e-01 6.52654666e-01
  8.80623252e-01]
 [2.03655634e-01 1.14307624e-01 6.17861129e-01 7.24811370e-01
  1.64249109e-01]
 [4.39933646e-01 4.23036506e-01 8.37663762e-02 4.12315747e-01
  1.97646841e-01]
 [2.47181537e-01 5.60444240e-01 2.10991134e-02 2.38380699e-05
  7.10894692e-01]
 [5.17299527e-02 4.67423185e-01 8.29034571e-01 5.20892656e-01
  5.26496712e-01]]


In [ ]:
print(D)

### Matrix multiplication
We saw last week that we could preform element-by-element multiplication using the multiplication operator `*`. To perform matrix multiplication we use `dot`. 

**Note:** If $X$ and $Y$ are matrices $XY$ is not necessarily equal to $YX$. The order is important for matrix multiplication. Additionally, the number of columns in the first matrix must match the number of rows in the second matrix.

In [ ]:
print(A.dot(B))

`dot` is a numpy function and method. It can be used, as above, as a method, or as a function, shown below. When used as a method, it is applied to a numpy array with an additional array as an input argument. When used as a function, we must use the numpy prefix `np` and give two input arguments, the two arrays to be multiplied. 

In [ ]:
print(np.dot(A,B))

In Numpy, many operations are implemented as both functions and methods. Both approaches give the same answer. It is a matter of personal preference which approach you use. 

In general, methods alter the object they are applied to, although this is not typically the case for Numpy methods. While functions leave the object itself unchanged and simply output the result of the operation.

#### Exercise 1
Create the following matrices in Python,
$$X=\begin{pmatrix} 1&2&3&4 \\ 2&4&6&8 \\ 3&6&9&12 \end{pmatrix}, \hspace{0.5cm}Y=\begin{pmatrix} 2&2&2 \\ 2&2&2 \\ 2&2&2 \\2&2&2 \end{pmatrix},$$
and compute the matrix product $XY$ and $YX$. Do they give the same result?

In [26]:
#non accesed exercise 
import numpy as np
X = np.array((range(1,5),[2,4,6,8],[3,6,9,12]))
Y =np.array(([2,2,2],[2,2,2],[2,2,2],[2,2,2]))
# print(X)
# print(Y)
print(X.dot(Y))

[[20 20 20]
 [40 40 40]
 [60 60 60]]


### Other useful matrix commands
The transpose of a matrix is an attribute of the matrix, accessed using `.T`. We can allow apply the transpose method to find the transpose.

In [27]:
print(A.T)
print(A.transpose())

[[0.62931286 0.29301315 0.11848313 0.85692086 0.19653696]
 [0.98444486 0.45093543 0.49458855 0.05628936 0.81938222]
 [0.1831626  0.44961356 0.22929457 0.42174352 0.71211918]
 [0.9414881  0.94800833 0.83935279 0.02514507 0.34760449]
 [0.23677709 0.15768588 0.51397033 0.25178105 0.22258346]]
[[0.62931286 0.29301315 0.11848313 0.85692086 0.19653696]
 [0.98444486 0.45093543 0.49458855 0.05628936 0.81938222]
 [0.1831626  0.44961356 0.22929457 0.42174352 0.71211918]
 [0.9414881  0.94800833 0.83935279 0.02514507 0.34760449]
 [0.23677709 0.15768588 0.51397033 0.25178105 0.22258346]]


We can extract the entries along the diagonal using the Numpy `diag` function or by applying the `diagonal` method to a Numpy array. Similarly, `trace` will compute the trace of the matrix (sum of diagonal entries).

In [28]:
print(D.diagonal())
print(D.trace())

[1. 1. 1. 1. 1.]
5.0


Many matrix operations live within the linear algebra module of Numpy. Modules can be imported wih shortcuts, just like packages.

In [33]:
import numpy.linalg as npl

Now we can use functions from this module with the prefix `npl`. Below are a couple of examples.

**Inverse**

In [31]:
print(npl.inv(A))

[[ 0.64201109 -0.02868955 -0.50155066  0.89255746 -0.51412839]
 [ 0.98379325 -1.05809825 -0.21965027 -0.51114907  0.78846299]
 [-1.12491297  1.08598086 -0.36985672  0.2863311   0.95744944]
 [-0.04704706  1.32088738  0.04043803 -0.26755881 -0.67643543]
 [-0.51601197 -1.61678114  2.3715886   0.5953214   0.03731886]]


**Determinant**

In [32]:
print(npl.det(B))

LinAlgError: Last 2 dimensions of the array must be square

**Eigenvalues**

In [ ]:
print(npl.eigvals(B))

### Matrix decomposition

Decomposing matrices is a very common operation in multivariate analysis. NumPy performs the usual Singular Value Decomposition (SVD) via `svd`, QR decomposition via `qr`, and Eigen decomposition via `eig`, as well as many others. Below is an illustration of QR decomposition:

In [ ]:
M = np.array([[3,6,1],[2,3,7],[9,2,5]])
my_qr = npl.qr(M)                       # Extract matrices
print(my_qr[0])                         # Q matrix 
print(my_qr[1])                         # R matrix
print(my_qr[0].dot(my_qr[1]))           # Check decomposition

### Solving matrix equations
A matrix equation is an equation of the form $$AX=B,$$where $A$ is an $n\times n$ matrix, $X$ is an $n\times m$ matrix and $B$ is an $n\times m$ matrix. We will typically be asked to solve for $X$ given a particular $A$ and $B$. 

Many novices when implementing the code take this as a requirement to call `npl.inv`, as $X=A^{-1}B$.
However, inverting matrices is a *very computationally demanding* task. Calling `npl.solve` is almost certainly faster.

In [37]:
A = np.random.rand(5,5)
print(A)

[[0.20030942 0.12990311 0.990644   0.21496815 0.76447263]
 [0.2888673  0.6964117  0.92204044 0.70186874 0.13983626]
 [0.81558743 0.0884806  0.02706435 0.55793913 0.88576011]
 [0.87308723 0.35858334 0.44617365 0.3288785  0.5347541 ]
 [0.29197515 0.93931884 0.71338778 0.62166651 0.49866888]]


In [38]:
B = np.random.rand(5,2)
print(B)

[[0.94608156 0.94865778]
 [0.34520873 0.20273013]
 [0.83302023 0.88809487]
 [0.75845607 0.1396863 ]
 [0.66842796 0.76928657]]


In [39]:
print(npl.solve(A,B))

[[ 0.23525533 -0.9200323 ]
 [ 0.15816907  0.08939952]
 [ 0.26847593 -0.16202728]
 [-0.290505    0.48473622]
 [ 0.88282598  1.54046606]]


In [34]:
A = np.random.rand(5,5)
B = np.random.rand(5,2)
print(npl.solve(A,B))

[[-1.25706227 -1.52843315]
 [-0.16175052 -1.61061667]
 [ 1.74647993 -0.13990437]
 [ 1.62291537 -0.3965789 ]
 [-0.76629119  5.39590778]]


In [40]:
X=npl.solve(A,B)
print(A.dot(X))
print(B)

[[0.94608156 0.94865778]
 [0.34520873 0.20273013]
 [0.83302023 0.88809487]
 [0.75845607 0.1396863 ]
 [0.66842796 0.76928657]]
[[0.94608156 0.94865778]
 [0.34520873 0.20273013]
 [0.83302023 0.88809487]
 [0.75845607 0.1396863 ]
 [0.66842796 0.76928657]]


We can use the iPython (interactive Python) command `timeit` to time how long it takes particular pieces of code to run. iPython commands are called with a `%`. `timeit` runs the code multiple times to get an accurate representation of how long the code takes to run.

In [41]:
%timeit npl.inv(A).dot(B)

48.4 µs ± 808 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [42]:
%timeit npl.solve(A,B)

31.5 µs ± 444 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [59]:
a= np.array(([2,1,-7],[6,-2,-1],[1,-5,2]))
b=np.array((['x'],['y'],['z']))
c= np.array(([10,5,8]))

print(b)

[['x']
 ['y']
 ['z']]


For smaller matrices there isn't a large time difference between the two approaches. Try increasing the number of rows and columns in $A$ and $B$ and see how long the two approaches take.

#### Exercise 2
Write the system of equations
$$ \begin{align} &2x+y-7z = 10 \\ &6x-2y-z = 5 \\ &x-5y+2z = 8 \end{align}$$
as a matrix system and use the solve function to solve for $x$, $y$ and $z$.

In [61]:
a= np.array(([2,1,-7],[6,-2,-1],[1,-5,2]))
#b=np.array((['x'],['y'],['z']))
c= np.array(([10,5,8]))

x= np.linalg.inv(a).dot(c)
print(x)

[-0.27272727 -2.39393939 -1.84848485]


## Random sampling
When performing statistical analysis we often make use of
*probability distributions*. Common probability distributions include:
* The uniform distribution (both discrete and continuous)
* The normal distribution
* The binomial distribution
* The Poisson distribution
* The gamma distribution

Make sure you're familiar with these so you can follow the next section and later material we cover.

In Python, random sampling is achieved using Numpy's random module. We will import it with the shortcut `npr`.

In [62]:
import numpy.random as npr

**Note:** We used the random module above to create matrices of random number, but did not use the shortcut as we had not defined it. 

Most of the things discussed below can also be acheived using the [random package](https://docs.python.org/3/library/random.html). We will focus soley on on Numpy's random module as it has greater functionality. 

### Sampling from random distributions
For the standard normal $N(0,1)$ and standard uniform $U(0,1)$ distribution, you only need to give NumPy the shape of the array you want.

In [63]:
print(npr.randn(3,4))
print(npr.rand(2,2))

[[ 0.77679802  0.57758201 -0.44599219  0.30490964]
 [ 0.05448944 -0.09020276  0.62498978 -0.32534912]
 [ 1.78911137  0.11785067  1.35489049 -0.62790377]]
[[0.50667987 0.30138944]
 [0.4576569  0.26550643]]


Other distributions require additional parameters, such as the mean $\mu$ and standard deviation $\sigma$ for the non-standard normal distribution $N(\mu,\sigma^2)$. When sampling from these distributions the shape is specified, as a tuple, using the size argument.

In [64]:
print(npr.normal(10,2,size=(3,2)))
print(npr.randint(0,100,size=(2,6)))

[[9.4809493  7.63599356]
 [9.84469058 7.84931107]
 [8.33845913 9.15324512]]
[[65 90 48 51 51 26]
 [97 59 76 12 77  0]]


In [72]:
a = npr.normal(10,2,size=(3,2))#argument 1 indicates the mean of in which data should be and 2nd parameter indicated the standard deviation or nearness of data if we want data to be near the mean(first argument) it can be set as low as needed higher the second argument further the data will be for the mean defined in first argument
print(a)
# print(npr.randint(0,100,size=(2,6)))

[[12.29809293  9.47823355]
 [13.06334526  7.73631927]
 [ 8.23074524 10.90322191]]


In [78]:
b= npr.randint(0,100,size=(2,6))#randint takes two arguments depending start and stop where first attribute indicates the start of the function second indicated the start 
print(b)

[[70 83 40 90 35 95]
 [12 33 16 36 74 83]]


### Taking a random sample
Often you have a list or array and you want to take a random rearrange of the entries. The Numpy random functions `permutation` and `shuffle` will do this for you. Permutation returns the random sample but leaves the original array unchanged, while shuffle changes the existing array.

In [83]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(npr.permutation(x))
print(x)

[ 3  2  7  6  4  9  8  5  1 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [84]:
npr.shuffle(x)
print(x)

[ 4  1  6  3  5  7  9  8 10  2]


If you want to randomly select some of the entries from an array, you should use the `choice` function.

In [85]:
print(npr.choice(x,2))

[8 5]


### Random seed
In practice, random number generators are pseudo-random. They rely on a deterministic algorithm and an initial value, known as a seed. Different seeds will produce different *seemingly random* results. Most random number generator uses the current system time as the default seed. Hence, every time you run the command `npr.rand()` you get a different "random" number.

When simulating data for checking or debugging purposes, we typically want to get the same random values every time we run the code. As such, it is useful to specify the seed value yourself. This can be done using the command `npr.seed(s)`, where the seed value *s* is given as an integer. Now every time you run the code below you get the same "random" number.

In [90]:
npr.seed()
print(npr.rand())

0.8195931178895832


**Note:** Using the seed command from the random package rather than Numpy's random module does not set the seed for functions/methods from Numpy's random module, and vice versa.

#### Exercise 3
Write a function `random_matrix` that outputs a matrix of random integers for a given seed. The function should have 5 arguments; the seed value $s$, the upper $u$ and lower $l$ bound for the range to sample over, and the number of rows $n$ and  columns $m$. The output should be an array with $n$ rows and $m$ columns, filled with integers between $l$ (inclusive) and $u$ (exclusive).

In [ ]:
import numpy.random as npr
def random_matrix(s,l,u,n,m):
    npr.seed(s)
    return npr.randint(l,u,size=(n,m))
    

In [91]:
npr.seed(101)
print(npr.randint(0,10,size=(1,10)))

[[1 6 7 9 8 4 8 5 0 5]]


## Pandas
Pandas is the main data analysis package we will use throughout this module. The two basic building blocks of Pandas are the structures *Series* and *DataFrame*. We import these functions separately to save typing the prefix every time we call them.

In [77]:
import pandas as pd
from pandas import Series, DataFrame

### Series
A *Series* is a 1D data object, like a vector or 1D Numpy array. We use the `Series` function to create a Series from a list, tuple or dict.

Printing out the Series, we see that the *index* is given along the left-hand side.

In [78]:
my_series = Series([1,2,3,4])
print(my_series)

0    1
1    2
2    3
3    4
dtype: int64


The *index* and *values* are attributes of the Series accessed using `.index` and `.values`, respectively.

In [94]:
print(my_series.index)
print(my_series.values)

RangeIndex(start=0, stop=4, step=1)
[1 2 3 4]


Series are elements are accessed and sliced in the usual way.

In [95]:
print(my_series[2])

3


In [96]:
print(my_series[1:3])

1    2
2    3
dtype: int64


Series are *mutable*, but the indices are not.

In [79]:
my_series[1]=5
print(my_series)

0    1
1    5
2    3
3    4
dtype: int64


In [80]:
my_series.index[1]=5

TypeError: Index does not support mutable operations

A key advantage of Series and DataFrames is that the you can specify index, as with a dict. 

In [81]:
my_series_2 = Series([6, 9, 2, 5],index=['a', 'd', 'b', 'c'])
print(my_series_2)

a    6
d    9
b    2
c    5
dtype: int64


Elements are accessed in the same was as for a dict.

In [100]:
print(my_series_2['c'])

5


We can also use *Boolean indexing* to return elements that meet a particular condition.

In [82]:
print(my_series_2[my_series_2 > 5])

a    6
d    9
dtype: int64


In [102]:
print(my_series_2 > 5)

a     True
d     True
b    False
c    False
dtype: bool


Adding two Series creates a new Series, with a line for each unique index. If the index exists in both Series, the values are added. Otherwise, the entry for that index is NaN, which stands for *Not a Number*.

In [83]:
my_series_3 = Series([1,2,3,4,5],index=['e', 'a', 'd', 'c','f'])
print(my_series_2+my_series_3)

a     8.0
b     NaN
c     9.0
d    12.0
e     NaN
f     NaN
dtype: float64


In [13]:
from pandas import Series
for i in range()
    

1    5
dtype: int64
2    10
dtype: int64
3    15
dtype: int64
4    20
dtype: int64


In [109]:
from pandas import Series
import pandas as pd
def multiples_five(n):
    s1 = pd.Series([]) 
    for i in range(1,n):
        data= 5*i
        if data < n:
            #indx = i=i+i
            s1 = s1.append(Series(data,index=[i]))
    return s1
     

In [110]:
multiples_five(30)

c:\Users\Rahul Matai\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  after removing the cwd from sys.path.


1     5
2    10
3    15
4    20
5    25
dtype: int64

The same holds of subtraction, multiplication and division.

#### Exercise 4
Write a function `multiples_five` that create a pandas Series where the entries are the multiples of 5 and the index corresponds to which multiple of 5 the entry in that row is. The function should have one input argument $max$, and the returned Series should include all multiples of 5 up to (but not including) $max$. For example, `multiples_five(24)` should return the Series with the entries 5, 10, 15, 20 and corresponding indices 1, 2, 3, 4.

### DataFrames

A DataFrame is the two-dimensional version of a Series. To create a DataFrame directly, simply pass a nested list or a dict to the function `DataFrame`.

In [ ]:
dict_1 = {'a': np.arange(5),'b': npr.rand(5),'c': npr.randint(0,10,size=(5))}
df_1 = DataFrame(dict_1)
print(df_1)

As with a Series, we can also specify the index when we create a DataFrame. We can even use one of the *key:value* pairs from our dict as the index.

In [117]:
iphone_dict = {'Name': ['iPhone', 'iPhone 3G', 'iPhone 3GS', 'iPhone 4', 'iPhone 4S', 'iPhone 5', 'iPhone 5C', 'iPhone 5S'],
    'Memory_MB': [128, 128, 256, 512, 512, 1024, 1024, 1024],
    'Weight_g': [135, 133, 135, 137, 140, 112, 132, 112],
    'Camera_MP': [2, 2, 3, 5, 8, 8, 8, 8],
    'Year': [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2013] }
iphone_df = DataFrame(iphone_dict,index=iphone_dict['Name'],columns=['Memory_MB','Weight_g','Camera_MP','Year'])
print(iphone_df)

            Memory_MB  Weight_g  Camera_MP  Year
iPhone            128       135          2  2007
iPhone 3G         128       133          2  2008
iPhone 3GS        256       135          3  2009
iPhone 4          512       137          5  2010
iPhone 4S         512       140          8  2011
iPhone 5         1024       112          8  2012
iPhone 5C        1024       132          8  2013
iPhone 5S        1024       112          8  2013


The columns are attributes of the DataFrame and can be accessed using the syntax `df.column`, where *df* is the name of the DataFrame and *column* is the name of the column you wish to access. You can also access columns with the syntax `df['column']`.

In [ ]:
print(iphone_df.Memory_MB)

In [ ]:
print(iphone_df['Weight_g'])

To access parts of a DataFrame we use `iloc` and `loc`. `iloc` is used to access a column or row based on its integer position, where as `loc` uses the label associated with it. When using `iloc` or `loc` the first index specifies the row and the second the column. If only one index is given, all entries for the row in question are returned.

In [ ]:
print(iphone_df.iloc[0])

In [ ]:
print(iphone_df.loc['iPhone 5C'])

In [ ]:
print(iphone_df.iloc[2:4,:2])

As with Series, the elements of a DataFrame are mutable, but the indices are not.

In [1]:
iphone_df.Camera_MP[4] = 6
print(iphone_df)

NameError: name 'iphone_df' is not defined

In [ ]:
iphone_df.Camera_MP = 6
print(iphone_df)

We can easily add columns to the DataFrame, and just as easily delete columns.

In [ ]:
iphone_df['Resolution_PPI'] = [163, 163, 163, 326, 326, 326, 326, 326]
print(iphone_df)

In [ ]:
del iphone_df['Camera_MP']
print(iphone_df)

### Pass-by-reference (again)
Pass-by-reference also applies to Series and DataFrames. If we extract part of the DataFrame and change it, the original DataFrame is also altered.

In [ ]:
df_2 = DataFrame({'x': [0,1,2,3],'y': [4,5,6,7],'z': [8,9,10,11]},index=('a','b','c','d'))
sample = df_2.x
sample[0:2] = 10
print(df_2)

To create a new object, for which changing it doesn't change the original use `.copy()`

In [ ]:
df_3 = DataFrame({'x': [0,1,2,3],'y': [4,5,6,7],'z': [8,9,10,11]},index=('a','b','c','d'))
sample2 = df_3.x.copy()
sample2[0:2] = 10
print(df_3)

### *in* operator
You can use the *in* operator to determine whether a value is in a particular object.

In [ ]:
print(1 in range(10))
print(10 in range(10))

It also works with Pandas objects provided you specify whether you want to search the values or the indices.

In [ ]:
print(512 in iphone_df.values)
print(512 in iphone_df.Weight_g.values)
print('iPhone' in iphone_df.index)

#### Exercise 5
Take the data from the table below and store it as a pandas DataFrame. Use the *Name* column as the row index, and the remaining column headings as the column indices. After creating the DataFrame, print out Darren's height.

| Name | Age | Height | Weight |
| ----------- | ----------- | ----------- | ----------- |
| Aaron      | 23      | 1.7   | 64     |
| Barry      | 36      | 2.1   | 99     |
| Catherine      | 27      | 1.8   | 68     |
| Darren      | 19      | 1.9   | 85     |
| Edel      | 41      | 1.7   | 102     |
| Francis      | 38      | 2.0   | 84     |
| George      | 57      | 1.8   | 87     |
| Helen      | 17      | 1.6   | 90     |
| Ian      | 28      | 1.7   | 78     |

In [119]:
human_dict = {'Name': ['Aaron', 'Barry', 'Catherine', 'Darren', 'Edel', 'Francis', 'George', 'Helen','Ian'],
    'Age': [23, 36, 27, 19, 41, 38, 57, 17,28],
    'Height': [1.7,2.1,1.8,1.9,1.7,2.0,1.8,1.6,1.7],
    'Weight': [64,99,68,85,102,84,87,90,78]}
people_df = pd.DataFrame(human_dict,index=human_dict['Name'],columns=['Age','Height','Weight'])
print(people_df[3:4]['Height'])


Darren    1.9
Name: Height, dtype: float64


In [ ]:
import numpy as np


In [ ]:
def matrix_multiplication(n):
    X = np.array(range(n**2+1)).reshape((n,n))
    Y = np.array(range(n**2,1,-1))
    print(Y.dot(X))